env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  import/no-named-as-default: off
  import/no-named-as-default-member: off
  arrow-body-style: off
  react/jsx-filename-extension: off
  spaced-comment: off
  import/prefer-default-export: off
  react/state-in-constructor: off
  react/require-default-props: off
  jsx-a11y/click-events-have-key-events: off
  jsx-a11y/no-static-element-interactions: off

